### ISSUE TITLE
Could not install pdfminer requirement on CentOS 6.4

### ISSUE THREAD

**Issue by rchekaluk** [opengovernment/legistar-scrape#1]
Downloading/unpacking pdfminer (from -r /u/apps/legistar-scrape-staging/requirements.txt (line 12))
  Could not find a version that satisfies the requirement pdfminer (from -r /u/apps/legistar-scrape-staging/requirements.txt (line 12)) (from versions: 20100829, 20101226, 20091219, 20100213, 20100327, 20100424, 20100322, 20101017, 20100104, 20110227, 20091129, 20091024, 20100131, 20100619p1, 20110515, dist-20080727, dist-20090201, dist-20080629, dist-20080429, dist-20080906, dist-20090110, dist-20090517, dist-20090117)
Cleaning up...
No distributions matching the version for pdfminer (from -r /u/apps/legistar-scrape-staging/requirements.txt (line 12))

**Comment by walter** [comment]
So what helped you get unblocked on this @rchekaluk?

Do you need something from @derekeder or is it a matter of digging more to find out how you can get pdfminer where you need it?

**Comment by rchekaluk** [comment]
I'm blocked on this, it's a matter of digging. If anybody can get an answer before me, feel free to share.

**Comment by derekeder** [comment]
@rchekaluk if there's no distribution for pdfminer, you'll probably have to build it from source: http://www.unixuser.org/~euske/python/pdfminer/#download

**Comment by rchekaluk** [comment]
I think the way to go is to modify requirements.txt to pull from a direct URL. Does this work, and if so can you do this?

```
diff --git a/requirements.txt b/requirements.txt
index 43c602c..a1165a6 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -12 +12 @@ BeautifulSoup4
-pdfminer
+https://pypi.python.org/packages/source/p/pdfminer/pdfminer-20110515.tar.gz#md5=f3905f801ed469900d9e5af959c7631a
```

**Comment by derekeder** [comment]
@rchekaluk made the change and verified it still works on my local machine. go ahead and give it a whirl on CentOS
